name: mnist-train
resources:
  cpus: 2
  memory: 4
setup: "uv pip install torch torchvision wandb transformerlab matplotlib"
run: "cd ~/mnist-train && python mnist_train.py"
envs:
  WANDB_API_KEY: "<your_wandb_api_key_here>"
  WANDB_PROJECT: "mnist-training-project"
  PYTHONUNBUFFERED: "1"
parameters:
  seed: "42"
  epochs: "1"
  batch_size: "64"
  test_batch_size: "1000"
  learning_rate: "0.01"
  momentum: "0.5"
  log_interval: "10"
  prediction_save_every_steps: "200"