name: gpt-oss-train-task
github_repo_url: https://github.com/transformerlab/transformerlab-examples
github_repo_dir: gpt-oss
resources:
  accelerators: "RTX3090:1"
setup: "uv pip install transformerlab datasets transformers==4.57.3 torch trl peft lm_eval==0.4.7;sudo apt update;sudo apt install -y libgl1 libglib2.0-0;"
run: "cd ~/gpt-oss && python train.py"
envs:
  PYTHONUNBUFFERED: "1"
  HF_TOKEN: "<your_huggingface_token_here>"
parameters:
  model_name: "openai/gpt-oss-20b"
  dataset: "HuggingFaceH4/Multilingual-Thinking"
  output_dir: "./output"
  enable_lora: false
  enable_profiling: false
  num_train_epochs: "1"
  per_device_train_batch_size: "1"
  gradient_accumulation_steps: "1"
  learning_rate: "2e-4"
  warmup_ratio: "0.03"
  save_steps: "500"
  max_steps: "-1"